// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  /** Migrate / CLI: dùng DIRECT_URL (Supabase port 5432). Không dùng pooler 6543 cho migrate. */
  datasource: {
    url:
      process.env["DIRECT_URL"]?.trim() ||
      process.env["DATABASE_URL"]?.trim(),
  },
});
